apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policy
  namespace: microservices-demo
data:
  policy.rego: |
    package microservices

    default allow = false

    # Allow product service to be called by anyone
    allow {
      input.path = ["products"]
    }

    allow {
      input.path = ["products", id]
    }

    allow {
      input.path = ["health"]
    }

    # Allow order service to be called by authorized clients
    allow {
      input.path = ["orders"]
      input.source_service = "apisix"
    }

    allow {
      input.path = ["orders", id]
      input.source_service = "apisix"
    }

    # Allow order service to call product service
    allow {
      input.path = ["products", id]
      input.source_service = "order-service"
      input.method = "GET"
    }

    allow {
      input.path = ["products", id]
      input.source_service = "order-service"
      input.method = "PUT"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: microservices-demo
  labels:
    app: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
      - name: opa
        image: openpolicyagent/opa:latest
        ports:
        - containerPort: 8181
        args:
        - "run"
        - "--server"
        - "--addr=:8181"
        - "/policies/policy.rego"
        volumeMounts:
        - readOnly: true
          mountPath: /policies
          name: opa-policy
      volumes:
      - name: opa-policy
        configMap:
          name: opa-policy
---
apiVersion: v1
kind: Service
metadata:
  name: opa
  namespace: microservices-demo
spec:
  selector:
    app: opa
  ports:
  - port: 8181
    targetPort: 8181