apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: microservices-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: ${DOCKER_REGISTRY}/order-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "yugabytedb"
        - name: DB_PORT
          value: "5433"
        - name: DB_USER
          value: "yugabyte"
        - name: DB_PASSWORD
          value: "yugabyte"
        - name: DB_NAME
          value: "yugabyte"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:8080"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: microservices-demo
spec:
  selector:
    app: order-service
  ports:
  - port: 8080
    targetPort: 8080